name: photosync
description: Synchronize your photos to a Nextcloud instance.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  flutter_secure_storage: ^5.0.2
  photo_manager: ^2.1.4
  intl: ^0.17.0
  exif: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#0082c9"
  image: assets/icons/icon.png
  color_dark: "#0082c9"
  image_dark: assets/icons/icon.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true
